In [2]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [91]:
car_noise_path='car_noise_specification_datasets.csv'
temp=pd.read_csv(car_noise_path,sep='\t',engine='python')
temp1=car_df.iloc[:,range(1,11)].copy()
noise_df=temp1.dropna(how='any')
columns=cars_df.columns.tolist()
temp

,Unnamed: 0,brand,model,spec,year,dB_at_idle,dB_at_50kmh,dB_at_80kmh,dB_at_100kmh,dB_at_120kmh,...,model_height_in_cqa,model_wheelbase_in_cqa,model_mpg_hwy_cqa,model_mpg_city_cqa,model_mpg_mixed_cqa,model_fuel_cap_g_cqa,make_display_cqa,make_country_cqa,ExtColors_cqa,IntColors_cqa
0,0,Abarth,500,1.4 16v T-Jet,2008.0,47.3,58.2,67.0,70.2,72.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Abarth,595,Competizione,2017.0,49.9,65.7,69.0,72.3,73.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Acura,MDX,3.5 V6,2013.0,41.7,51.7,57.9,61.2,64.0,...,68.2,108.3,27.0,19.0,NaN,20.9,Acura,USA,NaN,NaN
3,3,Acura,RDX,3.5 V6,2012.0,43.0,54.4,61.5,65.5,67.7,...,65.1,104.3,22.0,17.0,NaN,18.0,Acura,USA,NaN,NaN
4,4,Acura,RL,3.7 V6,2009.0,43.6,55.5,63.0,66.9,70.2,...,57.5,110.6,22.0,16.0,18.0,19.3,Acura,USA,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,1890,Volvo,XC90,2.0d,2017.0,47.9,64.7,65.5,66.3,67.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1891,1891,Volvo,XC90,T6,2017.0,39.9,55.8,60.0,64.3,65.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1892,1892,Volvo,XC90,D4,2018.0,43.9,53.5,59.1,64.3,66.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1893,1893,Volvo,XC90,D5,2018.0,47.1,55.6,60.9,65.3,67.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1894,1894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
print(columns)
noise_df.head()

['brand', 'model', 'spec', 'year', 'dB_at_idle', 'dB_at_50kmh', 'dB_at_80kmh', 'dB_at_100kmh', 'dB_at_120kmh', 'dB_at_140kmh']

,brand,model,spec,year,dB_at_idle,dB_at_50kmh,dB_at_80kmh,dB_at_100kmh,dB_at_120kmh,dB_at_140kmh
0,Abarth,500,1.4 16v T-Jet,2008.0,47.3,58.2,67.0,70.2,72.9,76.0
1,Abarth,595,Competizione,2017.0,49.9,65.7,69.0,72.3,73.1,75.8
2,Acura,MDX,3.5 V6,2013.0,41.7,51.7,57.9,61.2,64.0,66.8
3,Acura,RDX,3.5 V6,2012.0,43.0,54.4,61.5,65.5,67.7,69.9
4,Acura,RL,3.7 V6,2009.0,43.6,55.5,63.0,66.9,70.2,73.5

In [107]:
for col in noise_df.columns:
    print(col+'-----'+str(type(noise_df[col][0])))

brand-----<class 'str'>
model-----<class 'str'>
spec-----<class 'str'>
year-----<class 'numpy.float64'>
dB_at_idle-----<class 'numpy.float64'>
dB_at_50kmh-----<class 'numpy.float64'>
dB_at_80kmh-----<class 'numpy.float64'>
dB_at_100kmh-----<class 'numpy.float64'>
dB_at_120kmh-----<class 'numpy.float64'>
dB_at_140kmh-----<class 'numpy.float64'>

In [108]:
noise_df['dB_at_idle'].astype(float)

AttributeError: 'Series' object has no attribute 'as_type'

In [87]:
car_sales_path='Car_sales.csv'
temp_sales=pd.DataFrame(pd.read_csv(car_sales_path))
temp_sales2=temp_sales.drop(['__year_resale_value','Power_perf_factor','Wheelbase','Width','Length','Latest_Launch'],axis=1)
car_sales_df=temp_sales2.dropna(axis=0)
car_sales_df

,Manufacturer,Model,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Curb_weight,Fuel_capacity,Fuel_efficiency
0,Acura,Integra,16.919,Passenger,21.50,1.8,140.0,2.639,13.2,28.0
1,Acura,TL,39.384,Passenger,28.40,3.2,225.0,3.517,17.2,25.0
3,Acura,RL,8.588,Passenger,42.00,3.5,210.0,3.850,18.0,22.0
4,Audi,A4,20.397,Passenger,23.99,1.8,150.0,2.998,16.4,27.0
5,Audi,A6,18.780,Passenger,33.95,2.8,200.0,3.561,18.5,22.0
...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,Passenger,24.40,1.9,160.0,3.042,15.8,25.0
153,Volvo,S70,15.245,Passenger,27.50,2.4,168.0,3.208,17.9,25.0
154,Volvo,V70,17.531,Passenger,28.80,2.4,168.0,3.259,17.9,25.0
155,Volvo,C70,3.493,Passenger,45.50,2.3,236.0,3.601,18.5,23.0
156,Volvo,S80,18.969,Passenger,36.00,2.9,201.0,3.600,21.1,24.0

In [106]:
for col in car_sales_df.columns:
    print(col+'-----'+str(type(car_sales_df[col][0])))

Manufacturer-----<class 'str'>
Model-----<class 'str'>
Sales_in_thousands-----<class 'numpy.float64'>
Vehicle_type-----<class 'str'>
Price_in_thousands-----<class 'numpy.float64'>
Engine_size-----<class 'numpy.float64'>
Horsepower-----<class 'numpy.float64'>
Curb_weight-----<class 'numpy.float64'>
Fuel_capacity-----<class 'numpy.float64'>
Fuel_efficiency-----<class 'numpy.float64'>