In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [2]:
car_noise_path='car_noise_specification_datasets.csv'
temp=pd.read_csv(car_noise_path,sep='\t',engine='python')
temp1=temp.iloc[:,range(1,11)].copy()
noise_df=temp1.dropna(how='any')
noise_df.drop_duplicates(subset=['model'])
columns=temp1.columns
temp1

,brand,model,spec,year,dB_at_idle,dB_at_50kmh,dB_at_80kmh,dB_at_100kmh,dB_at_120kmh,dB_at_140kmh
0,Abarth,500,1.4 16v T-Jet,2008.0,47.3,58.2,67.0,70.2,72.9,76.0
1,Abarth,595,Competizione,2017.0,49.9,65.7,69.0,72.3,73.1,75.8
2,Acura,MDX,3.5 V6,2013.0,41.7,51.7,57.9,61.2,64.0,66.8
3,Acura,RDX,3.5 V6,2012.0,43.0,54.4,61.5,65.5,67.7,69.9
4,Acura,RL,3.7 V6,2009.0,43.6,55.5,63.0,66.9,70.2,73.5
...,...,...,...,...,...,...,...,...,...,...
1890,Volvo,XC90,2.0d,2017.0,47.9,64.7,65.5,66.3,67.2,70.6
1891,Volvo,XC90,T6,2017.0,39.9,55.8,60.0,64.3,65.2,68.6
1892,Volvo,XC90,D4,2018.0,43.9,53.5,59.1,64.3,66.7,68.8
1893,Volvo,XC90,D5,2018.0,47.1,55.6,60.9,65.3,67.7,69.8
1894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
noise_df=noise_df.drop_duplicates(subset=['model'],ignore_index=True)
print(columns)
noise_df.head(20)

Index(['brand', 'model', 'spec', 'year', 'dB_at_idle', 'dB_at_50kmh',
       'dB_at_80kmh', 'dB_at_100kmh', 'dB_at_120kmh', 'dB_at_140kmh'],
      dtype='object')

,brand,model,spec,year,dB_at_idle,dB_at_50kmh,dB_at_80kmh,dB_at_100kmh,dB_at_120kmh,dB_at_140kmh
0,Abarth,500,1.4 16v T-Jet,2008.0,47.3,58.2,67.0,70.2,72.9,76.0
1,Abarth,595,Competizione,2017.0,49.9,65.7,69.0,72.3,73.1,75.8
2,Acura,MDX,3.5 V6,2013.0,41.7,51.7,57.9,61.2,64.0,66.8
3,Acura,RDX,3.5 V6,2012.0,43.0,54.4,61.5,65.5,67.7,69.9
4,Acura,RL,3.7 V6,2009.0,43.6,55.5,63.0,66.9,70.2,73.5
5,Acura,RLX,3.5 V6,2013.0,39.5,49.7,56.0,59.3,62.4,65.6
6,Acura,TL,3.5 V6,2009.0,40.2,54.5,63.3,68.6,70.1,71.7
7,Acura,TSX,2.4,2009.0,42.2,54.0,61.2,65.2,67.9,70.5
8,Alfa Romeo,147,1.9 JTDm,2008.0,44.9,55.2,63.5,67.0,69.1,71.4
9,Alfa Romeo,159,2.2 JTS,2008.0,44.5,54.8,63.0,67.2,68.5,70.2
10,Alfa Romeo,4C,Ã‚,2014.0,50.1,75.2,76.1,76.9,81.3,83.3
11,Alfa Romeo,Giulia,2.1d,2017.0,44.9,59.8,63.5,67.3,69.1,72.7
12,Alfa Romeo,Giulietta,1.4,2010.0,44.1,60.5,64.0,66.0,68.5,71.5
13,Alfa Romeo,GT,1.9 JTDm Q2,2008.0,41.9,51.5,59.2,63.8,64.4,65.3
14,Alfa Romeo,MiTo,1.4 Turbo 155,2008.0,45.1,55.5,63.8,68.5,69.4,70.7
15,Alfa Romeo,Stelvio,2.0,2017.0,42.9,57.8,61.0,64.3,66.2,69.6
16,Alpina,B7,Ã‚,2011.0,43.9,54.8,61.5,65.5,67.1,68.8
17,Aston Martin,Rapide,5.9 V12,2013.0,52.2,58.1,62.2,63.1,68.6,74.1
18,Audi,A1,1.4 TFSI S tronic,2010.0,39.4,62.2,64.4,66.8,69.1,71.9
19,Audi,A3,2.0 TFSI Cabrio,2008.0,46.1,62.0,63.0,65.0,68.0,68.2

In [4]:
for num in range(len(noise_df)):
    noise_df.iloc[num,0]=noise_df.iloc[num,0]+'_'+noise_df.iloc[num,1]
noise_df=noise_df.drop(['model'],axis=1)
noise_df=noise_df.rename(columns={'brand':'Manufacturer_Model'})
noise_df=noise_df.set_index('Manufacturer_Model')

In [5]:
noise_df

,spec,year,dB_at_idle,dB_at_50kmh,dB_at_80kmh,dB_at_100kmh,dB_at_120kmh,dB_at_140kmh
Manufacturer_Model,,,,,,,,
Abarth_500,1.4 16v T-Jet,2008.0,47.3,58.2,67.0,70.2,72.9,76.0
Abarth_595,Competizione,2017.0,49.9,65.7,69.0,72.3,73.1,75.8
Acura_MDX,3.5 V6,2013.0,41.7,51.7,57.9,61.2,64.0,66.8
Acura_RDX,3.5 V6,2012.0,43.0,54.4,61.5,65.5,67.7,69.9
Acura_RL,3.7 V6,2009.0,43.6,55.5,63.0,66.9,70.2,73.5
...,...,...,...,...,...,...,...,...
Volvo_V90,T5 Stationcar,2016.0,46.2,53.8,60.8,63.8,67.4,69.5
Volvo_XC40,D4,2018.0,43.9,54.0,59.7,65.3,67.7,69.8
Volvo_XC60,D5 Geartronic,2008.0,45.4,54.8,60.5,63.5,67.0,69.3
Volvo_XC70,D5,2008.0,43.2,53.2,61.2,65.5,66.5,67.9
Volvo_XC90,D5,2015.0,44.1,55.8,61.5,64.2,67.9,70.0

In [6]:
for col in noise_df.columns:
    print(col+'-----'+str(type(noise_df[col][0])))

spec-----<class 'str'>
year-----<class 'numpy.float64'>
dB_at_idle-----<class 'numpy.float64'>
dB_at_50kmh-----<class 'numpy.float64'>
dB_at_80kmh-----<class 'numpy.float64'>
dB_at_100kmh-----<class 'numpy.float64'>
dB_at_120kmh-----<class 'numpy.float64'>
dB_at_140kmh-----<class 'numpy.float64'>

In [7]:
noise_df['year']=noise_df['year'].astype(int)

In [8]:
for col in noise_df.columns:
    print(col+'-----'+str(type(noise_df[col][0])))

spec-----<class 'str'>
year-----<class 'numpy.int32'>
dB_at_idle-----<class 'numpy.float64'>
dB_at_50kmh-----<class 'numpy.float64'>
dB_at_80kmh-----<class 'numpy.float64'>
dB_at_100kmh-----<class 'numpy.float64'>
dB_at_120kmh-----<class 'numpy.float64'>
dB_at_140kmh-----<class 'numpy.float64'>

In [9]:
car_sales_path='Car_sales.csv'
temp_sales=pd.DataFrame(pd.read_csv(car_sales_path))
temp_sales2=temp_sales.drop(['__year_resale_value','Power_perf_factor','Wheelbase','Width','Length','Latest_Launch'],axis=1)
car_sales_df=temp_sales2.dropna(axis=0)
for num in range(len(car_sales_df)):
    car_sales_df.iloc[num,0]=car_sales_df.iloc[num,0]+'_'+car_sales_df.iloc[num,1]
car_sales_df=car_sales_df.drop(['Model'],axis=1)
car_sales_df=car_sales_df.rename(columns={'Manufacturer':'Manufacturer_Model'})
car_sales_df=car_sales_df.set_index('Manufacturer_Model')

C:\Users\A\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [10]:
for col in car_sales_df.columns:
    print(col+'-----'+str(type(car_sales_df[col][0])))

Sales_in_thousands-----<class 'numpy.float64'>
Vehicle_type-----<class 'str'>
Price_in_thousands-----<class 'numpy.float64'>
Engine_size-----<class 'numpy.float64'>
Horsepower-----<class 'numpy.float64'>
Curb_weight-----<class 'numpy.float64'>
Fuel_capacity-----<class 'numpy.float64'>
Fuel_efficiency-----<class 'numpy.float64'>

In [11]:
#car_sales_df['Horsepower']=car_sales_df['Horsepower'].astype(int)
car_sales_df['Fuel_efficiency']=car_sales_df['Fuel_efficiency'].astype(int)

In [12]:
car_sales_df

,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Curb_weight,Fuel_capacity,Fuel_efficiency
Manufacturer_Model,,,,,,,,
Acura_Integra,16.919,Passenger,21.50,1.8,140.0,2.639,13.2,28
Acura_TL,39.384,Passenger,28.40,3.2,225.0,3.517,17.2,25
Acura_RL,8.588,Passenger,42.00,3.5,210.0,3.850,18.0,22
Audi_A4,20.397,Passenger,23.99,1.8,150.0,2.998,16.4,27
Audi_A6,18.780,Passenger,33.95,2.8,200.0,3.561,18.5,22
...,...,...,...,...,...,...,...,...
Volvo_V40,3.545,Passenger,24.40,1.9,160.0,3.042,15.8,25
Volvo_S70,15.245,Passenger,27.50,2.4,168.0,3.208,17.9,25
Volvo_V70,17.531,Passenger,28.80,2.4,168.0,3.259,17.9,25
Volvo_C70,3.493,Passenger,45.50,2.3,236.0,3.601,18.5,23
Volvo_S80,18.969,Passenger,36.00,2.9,201.0,3.600,21.1,24

In [13]:
rds_connection_string = "taylor:{redacted}@localhost:5432/etl-challenge"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [14]:
engine.table_names()

['car_noise_tb', 'car_sales_tb', 'car_noise', 'car_sales']

In [ ]:
noise_df.to_sql(name='car_noise_tb', con=engine, if_exists='append', index=True)

In [ ]:
car_sales_df.to_sql(name='car_sales_tb', con=engine, if_exists='append', index=True)